spring.application.name=LengBD
server.port-=80

spring.datasource.url=jdbc:oracle:thin:@iiq2026_medium
spring.datasource.hikari.data-source-properties.oracle.net.tns_admin=./src/main/resources/wallet
spring.datasource.hikari.data-source-properties.oracle.net.wallet_location=./src/main/resources/wallet

spring.datasource.username=ADMIN
spring.datasource.password=Amhc301004_!

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false

logging.level.org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator=DEBUG
logging.level.com.zaxxer.hikari=DEBUG